apiVersion: v1
kind: Service
metadata:
  name: salman-employee
  namespace: webapp
spec:
  selector:
    app: employee
    version: v1  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort

