apiVersion: v1
kind: Service
metadata:
  name: salman-employee
  namespace: webapp
spec:
  selector:
    app: employee
    version: v2 # Add version selector for v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort

